const productsArrivals = [
  {
    id: 1,
    title: "T-SHIRT WITH TAPE DETAILS",
    images: ["./images/arrivals/frame.png"],
    rating: 4.5,
    price: 120,
    text: "Stylish cotton t-shirt with modern tape details for everyday comfort.",
  },
  {
    id: 2,
    title: "HOODED SWEATSHIRT",
    images: ["./images/arrivals/frame.png"],
    rating: 5,
    price: 200,
    oldPrice: 250,
    salePercent: "-20%",
    text: "Cozy hooded sweatshirt with soft lining and casual design.",
  },
  {
    id: 3,
    title: "SPORTS SHOES",
    images: ["./images/arrivals/frame.png"],
    rating: 3.5,
    price: 180,
    oldPrice: 220,
    salePercent: "-18%",
    text: "Lightweight sports shoes designed for comfort and performance.",
  },
  {
    id: 4,
    title: "CLASSIC JEANS",
    images: ["./images/arrivals/frame.png"],
    rating: 4,
    price: 140,
    text: "Durable and stylish jeans with a classic straight cut.",
  },
  {
    id: 5,
    title: "SUMMER SHORTS",
    images: ["./images/arrivals/frame.png"],
    rating: 4.2,
    price: 90,
    oldPrice: 120,
    salePercent: "-25%",
    text: "Light cotton shorts ideal for warm summer days.",
  },
  {
    id: 6,
    title: "COTTON T-SHIRT",
    images: ["./images/arrivals/frame.png"],
    rating: 4.8,
    price: 110,
    oldPrice: 130,
    salePercent: "-15%",
    text: "Breathable cotton t-shirt with a minimalist look.",
  },
  {
    id: 7,
    title: "LEATHER JACKET",
    images: ["./images/arrivals/frame.png"],
    rating: 5,
    price: 350,
    oldPrice: 400,
    salePercent: "-12%",
    text: "Premium leather jacket with modern style and comfort.",
  },
  {
    id: 8,
    title: "CAP WITH LOGO",
    images: ["./images/arrivals/frame.png"],
    rating: 3.8,
    price: 50,
    oldPrice: 65,
    salePercent: "-23%",
    text: "Casual cap with embroidered logo and adjustable fit.",
  },
  {
    id: 9,
    title: "DENIM SKIRT",
    images: ["./images/arrivals/frame.png"],
    rating: 4.3,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
    text: "Trendy denim skirt with classic pockets and durable fabric.",
  },
  {
    id: 10,
    title: "SNEAKERS CLASSIC",
    images: ["./images/arrivals/frame.png"],
    rating: 4.7,
    price: 210,
    oldPrice: 250,
    salePercent: "-16%",
    text: "Classic sneakers with a comfortable sole for everyday wear.",
  },
  {
    id: 11,
    title: "TRACKSUIT",
    images: ["./images/arrivals/frame.png"],
    rating: 4.6,
    price: 240,
    oldPrice: 300,
    salePercent: "-20%",
    text: "Sporty tracksuit with modern design and breathable fabric.",
  },
  {
    id: 12,
    title: "LEATHER BELT",
    images: ["./images/arrivals/frame.png"],
    rating: 4.4,
    price: 80,
    oldPrice: 95,
    salePercent: "-15%",
    text: "High-quality leather belt with metal buckle.",
  },
  {
    id: 13,
    title: "COTTON HOODIE",
    images: ["./images/arrivals/frame.png"],
    rating: 4.5,
    price: 190,
    oldPrice: 230,
    salePercent: "-17%",
    text: "Soft cotton hoodie with classic style and warmth.",
  },
  {
    id: 14,
    title: "CLASSIC WATCH",
    images: ["./images/arrivals/frame.png"],
    rating: 4.9,
    price: 450,
    oldPrice: 520,
    salePercent: "-13%",
    text: "Elegant classic wristwatch with premium design.",
  },
  {
    id: 15,
    title: "SUNGLASSES",
    images: ["./images/arrivals/frame.png"],
    rating: 4.3,
    price: 120,
    oldPrice: 140,
    salePercent: "-14%",
    text: "Stylish sunglasses with UV protection lenses.",
  },
  {
    id: 16,
    title: "SPORTS BACKPACK",
    images: ["./images/arrivals/frame.png"],
    rating: 4.7,
    price: 170,
    oldPrice: 210,
    salePercent: "-19%",
    text: "Durable backpack with multiple compartments for sports gear.",
  },
  {
    id: 17,
    title: "CASUAL SHOES",
    images: ["./images/arrivals/frame.png"],
    rating: 4.5,
    price: 190,
    oldPrice: 230,
    salePercent: "-17%",
    text: "Casual shoes with modern design and comfortable sole.",
  },
  {
    id: 18,
    title: "WINTER JACKET",
    images: ["./images/arrivals/frame.png"],
    rating: 5,
    price: 400,
    oldPrice: 460,
    salePercent: "-13%",
    text: "Warm winter jacket with water-resistant fabric.",
  },
  {
    id: 19,
    title: "LEATHER WALLET",
    images: ["./images/arrivals/frame.png"],
    rating: 4.6,
    price: 95,
    oldPrice: 110,
    salePercent: "-14%",
    text: "Compact leather wallet with multiple card slots.",
  },
  {
    id: 20,
    title: "SPORTS CAP",
    images: ["./images/arrivals/frame.png"],
    rating: 3.5,
    price: 55,
    oldPrice: 70,
    salePercent: "-21%",
    text: "Lightweight sports cap for casual and active wear.",
  },
]

const productsSelling = [
  {
    id: 21,
    title: "KNIT SWEATER",
    images: ["./images/selling/image.png"],
    rating: 4.6,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
    text: "Warm knitted sweater made from soft material.",
  },
  {
    id: 22,
    title: "DENIM JACKET",
    images: ["./images/selling/image.png"],
    rating: 5,
    price: 280,
    oldPrice: 320,
    salePercent: "-13%",
    text: "Classic denim jacket with stylish cut.",
  },
  {
    id: 23,
    title: "SPORTY LEGGINGS",
    images: ["./images/selling/image.png"],
    rating: 4.1,
    price: 95,
    oldPrice: 120,
    salePercent: "-21%",
    text: "Comfortable sporty leggings with stretch fabric.",
  },
  {
    id: 24,
    title: "BASIC POLO SHIRT",
    images: ["./images/selling/image.png"],
    rating: 3.9,
    price: 70,
    text: "Basic cotton polo shirt with casual design.",
  },
  {
    id: 25,
    title: "FLORAL DRESS",
    images: ["./images/selling/image.png"],
    rating: 4.5,
    price: 150,
    oldPrice: 180,
    salePercent: "-17%",
    text: "Light floral dress perfect for summer outings.",
  },
  {
    id: 26,
    title: "RUNNING SNEAKERS",
    images: ["./images/selling/image.png"],
    rating: 4.8,
    price: 220,
    oldPrice: 260,
    salePercent: "-15%",
    text: "Running sneakers with soft cushioning and grip sole.",
  },
  {
    id: 27,
    title: "LEATHER BELT",
    images: ["./images/selling/image.png"],
    rating: 4.3,
    price: 45,
    text: "Durable leather belt with classic buckle.",
  },
  {
    id: 28,
    title: "BASEBALL CAP",
    images: ["./images/selling/image.png"],
    rating: 3.7,
    price: 35,
    oldPrice: 50,
    salePercent: "-30%",
    text: "Baseball cap with adjustable strap and breathable fabric.",
  },
  {
    id: 29,
    title: "COTTON SHIRT",
    images: ["./images/selling/image.png"],
    rating: 4.2,
    price: 85,
    oldPrice: 100,
    salePercent: "-15%",
    text: "Soft cotton shirt with a comfortable fit.",
  },
  {
    id: 30,
    title: "SLIM FIT TROUSERS",
    images: ["./images/selling/image.png"],
    rating: 4.9,
    price: 190,
    oldPrice: 220,
    salePercent: "-14%",
    text: "Slim fit trousers for a modern and elegant look.",
  },
]

const productsLikes = [
  {
    id: 31,
    title: "KNIT SWEATER",
    images: ["./images/selling/image.png"],
    rating: 4.6,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
    text: "Warm knitted sweater made from soft material.",
  },
  {
    id: 32,
    title: "DENIM JACKET",
    images: ["./images/selling/image.png"],
    rating: 5,
    price: 280,
    oldPrice: 320,
    salePercent: "-13%",
    text: "Classic denim jacket with stylish cut.",
  },
  {
    id: 33,
    title: "SPORTY LEGGINGS",
    images: ["./images/selling/image.png"],
    rating: 4.1,
    price: 95,
    oldPrice: 120,
    salePercent: "-21%",
    text: "Comfortable sporty leggings with stretch fabric.",
  },
  {
    id: 34,
    title: "BASIC POLO SHIRT",
    images: ["./images/selling/image.png"],
    rating: 3.9,
    price: 70,
    text: "Basic cotton polo shirt with casual design.",
  },
]

const productsCategory = [
  {
    id: 35,
    title: "T-SHIRT WITH TAPE DETAILS",
    images: ["./images/category/image-1.png"],
    rating: 4.5,
    price: 120,
    text: "Stylish cotton t-shirt with modern tape details.",
  },
  {
    id: 36,
    title: "HOODED SWEATSHIRT",
    images: ["./images/category/image-2.png"],
    rating: 5,
    price: 200,
    oldPrice: 250,
    salePercent: "-20%",
    text: "Cozy hooded sweatshirt with soft lining.",
  },
  {
    id: 37,
    title: "SPORTS SHOES",
    images: ["./images/category/image-3.png"],
    rating: 3.5,
    price: 180,
    oldPrice: 220,
    salePercent: "-18%",
    text: "Comfortable sports shoes for active lifestyle.",
  },
  {
    id: 38,
    title: "CLASSIC JEANS",
    images: ["./images/category/image-4.png"],
    rating: 4,
    price: 140,
    text: "Classic denim jeans with durable fabric.",
  },
  {
    id: 39,
    title: "SUMMER SHORTS",
    images: ["./images/category/image-5.png"],
    rating: 4.2,
    price: 90,
    oldPrice: 120,
    salePercent: "-25%",
    text: "Light shorts perfect for hot weather.",
  },
  {
    id: 40,
    title: "COTTON T-SHIRT",
    images: ["./images/category/image-6.png"],
    rating: 4.8,
    price: 110,
    oldPrice: 130,
    salePercent: "-15%",
    text: "Soft cotton t-shirt with simple design.",
  },
  {
    id: 41,
    title: "LEATHER JACKET",
    images: ["./images/category/image-7.png"],
    rating: 5,
    price: 350,
    oldPrice: 400,
    salePercent: "-12%",
    text: "Premium leather jacket with classic cut.",
  },
  {
    id: 42,
    title: "CAP WITH LOGO",
    images: ["./images/category/image-8.png"],
    rating: 3.8,
    price: 50,
    oldPrice: 65,
    salePercent: "-23%",
    text: "Cap with logo print and adjustable strap.",
  },
  {
    id: 43,
    title: "DENIM SKIRT",
    images: ["./images/category/image-9.png"],
    rating: 4.3,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
    text: "Trendy denim skirt with classic style.",
  },
  {
    id: 44,
    title: "SNEAKERS CLASSIC",
    images: ["./images/category/image-10.png"],
    rating: 4.7,
    price: 210,
    oldPrice: 250,
    salePercent: "-16%",
    text: "Comfortable sneakers with modern design.",
  },
  {
    id: 45,
    title: "TRACKSUIT",
    images: ["./images/category/image-11.png"],
    rating: 4.6,
    price: 240,
    oldPrice: 300,
    salePercent: "-20%",
    text: "Stylish tracksuit for sport and leisure.",
  },
  {
    id: 46,
    title: "LEATHER BELT",
    images: ["./images/category/image-12.png"],
    rating: 4.4,
    price: 80,
    oldPrice: 95,
    salePercent: "-15%",
    text: "Classic leather belt with sturdy buckle.",
  },
]
