const productsArrivals = [
  {
    id: 1,
    title: "T-SHIRT WITH TAPE DETAILS",
    image: "/images/arrivals/frame.png",
    rating: 4.5,
    price: 120,
  },
  {
    id: 2,
    title: "HOODED SWEATSHIRT",
    image: "/images/arrivals/frame.png",
    rating: 5,
    price: 200,
    oldPrice: 250,
    salePercent: "-20%",
  },
  {
    id: 3,
    title: "SPORTS SHOES",
    image: "/images/arrivals/frame.png",
    rating: 3.5,
    price: 180,
    oldPrice: 220,
    salePercent: "-18%",
  },
  {
    id: 4,
    title: "CLASSIC JEANS",
    image: "/images/arrivals/frame.png",
    rating: 4,
    price: 140,
  },
  {
    id: 5,
    title: "SUMMER SHORTS",
    image: "/images/arrivals/frame.png",
    rating: 4.2,
    price: 90,
    oldPrice: 120,
    salePercent: "-25%",
  },
  {
    id: 6,
    title: "COTTON T-SHIRT",
    image: "/images/arrivals/frame.png",
    rating: 4.8,
    price: 110,
    oldPrice: 130,
    salePercent: "-15%",
  },
  {
    id: 7,
    title: "LEATHER JACKET",
    image: "/images/arrivals/frame.png",
    rating: 5,
    price: 350,
    oldPrice: 400,
    salePercent: "-12%",
  },
  {
    id: 8,
    title: "CAP WITH LOGO",
    image: "/images/arrivals/frame.png",
    rating: 3.8,
    price: 50,
    oldPrice: 65,
    salePercent: "-23%",
  },
  {
    id: 9,
    title: "DENIM SKIRT",
    image: "/images/arrivals/frame.png",
    rating: 4.3,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
  },
  {
    id: 10,
    title: "SNEAKERS CLASSIC",
    image: "/images/arrivals/frame.png",
    rating: 4.7,
    price: 210,
    oldPrice: 250,
    salePercent: "-16%",
  },
  {
    id: 11,
    title: "TRACKSUIT",
    image: "/images/arrivals/frame.png",
    rating: 4.6,
    price: 240,
    oldPrice: 300,
    salePercent: "-20%",
  },
  {
    id: 12,
    title: "LEATHER BELT",
    image: "/images/arrivals/frame.png",
    rating: 4.4,
    price: 80,
    oldPrice: 95,
    salePercent: "-15%",
  },
  {
    id: 13,
    title: "COTTON HOODIE",
    image: "/images/arrivals/frame.png",
    rating: 4.5,
    price: 190,
    oldPrice: 230,
    salePercent: "-17%",
  },
  {
    id: 14,
    title: "CLASSIC WATCH",
    image: "/images/arrivals/frame.png",
    rating: 4.9,
    price: 450,
    oldPrice: 520,
    salePercent: "-13%",
  },
  {
    id: 15,
    title: "SUNGLASSES",
    image: "/images/arrivals/frame.png",
    rating: 4.3,
    price: 120,
    oldPrice: 140,
    salePercent: "-14%",
  },
  {
    id: 16,
    title: "SPORTS BACKPACK",
    image: "/images/arrivals/frame.png",
    rating: 4.7,
    price: 170,
    oldPrice: 210,
    salePercent: "-19%",
  },
  {
    id: 17,
    title: "CASUAL SHOES",
    image: "/images/arrivals/frame.png",
    rating: 4.5,
    price: 190,
    oldPrice: 230,
    salePercent: "-17%",
  },
  {
    id: 18,
    title: "WINTER JACKET",
    image: "/images/arrivals/frame.png",
    rating: 5,
    price: 400,
    oldPrice: 460,
    salePercent: "-13%",
  },
  {
    id: 19,
    title: "LEATHER WALLET",
    image: "/images/arrivals/frame.png",
    rating: 4.6,
    price: 95,
    oldPrice: 110,
    salePercent: "-14%",
  },
  {
    id: 20,
    title: "SPORTS CAP",
    image: "/images/arrivals/frame.png",
    rating: 3.5,
    price: 55,
    oldPrice: 70,
    salePercent: "-21%",
  },
]
const productsSelling = [
  {
    id: 1,
    title: "KNIT SWEATER",
    image: "/images/selling/image.png",
    rating: 4.6,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
  },
  {
    id: 2,
    title: "DENIM JACKET",
    image: "/images/selling/image.png",
    rating: 5,
    price: 280,
    oldPrice: 320,
    salePercent: "-13%",
  },
  {
    id: 3,
    title: "SPORTY LEGGINGS",
    image: "/images/selling/image.png",
    rating: 4.1,
    price: 95,
    oldPrice: 120,
    salePercent: "-21%",
  },
  {
    id: 4,
    title: "BASIC POLO SHIRT",
    image: "/images/selling/image.png",
    rating: 3.9,
    price: 70,
  },
  {
    id: 5,
    title: "FLORAL DRESS",
    image: "/images/selling/image.png",
    rating: 4.5,
    price: 150,
    oldPrice: 180,
    salePercent: "-17%",
  },
  {
    id: 6,
    title: "RUNNING SNEAKERS",
    image: "/images/selling/image.png",
    rating: 4.8,
    price: 220,
    oldPrice: 260,
    salePercent: "-15%",
  },
  {
    id: 7,
    title: "LEATHER BELT",
    image: "/images/selling/image.png",
    rating: 4.3,
    price: 45,
  },
  {
    id: 8,
    title: "BASEBALL CAP",
    image: "/images/selling/image.png",
    rating: 3.7,
    price: 35,
    oldPrice: 50,
    salePercent: "-30%",
  },
  {
    id: 9,
    title: "COTTON SHIRT",
    image: "/images/selling/image.png",
    rating: 4.2,
    price: 85,
    oldPrice: 100,
    salePercent: "-15%",
  },
  {
    id: 10,
    title: "SLIM FIT TROUSERS",
    image: "/images/selling/image.png",
    rating: 4.9,
    price: 190,
    oldPrice: 220,
    salePercent: "-14%",
  },
]
const productslikes = [
  {
    id: 1,
    title: "KNIT SWEATER",
    image: "/images/selling/image.png",
    rating: 4.6,
    price: 130,
    oldPrice: 160,
    salePercent: "-19%",
  },
  {
    id: 2,
    title: "DENIM JACKET",
    image: "/images/selling/image.png",
    rating: 5,
    price: 280,
    oldPrice: 320,
    salePercent: "-13%",
  },
  {
    id: 3,
    title: "SPORTY LEGGINGS",
    image: "/images/selling/image.png",
    rating: 4.1,
    price: 95,
    oldPrice: 120,
    salePercent: "-21%",
  },
  {
    id: 4,
    title: "BASIC POLO SHIRT",
    image: "/images/selling/image.png",
    rating: 3.9,
    price: 70,
  },
]
